### ISSUE TITLE
Learning full graph

### ISSUE THREAD

**Issue by nghson** [azamikram/rcd#4]
Can RCD learn the full graph by setting localized to False? I've tried that and get the graph returned by u.top_k_rc from Phase 2 of run_multi_phase, but the graph is still only the neighbors of F-node. Could you please clarify this?

**Comment by nghson** [comment]
I just realized that I can get the full graph by setting localized=False and gamma=number of total variables. However, the graph is not quite right in my test case...

**Comment by azamikram** [comment]
I'm not sure what you are trying to achieve but RCD only focuses on estimating the interventional target and not learning the complete graph. Although setting `localized` to false will disable the localized approach, the output of RCD will still consist of the descendants of the F-node. Additionally, setting `gamma` to `n` will eliminate the hierarchical component of RCD, as there will only be one subset. Using both of these options together, (`localized=False`, and `gamma=n`), would simply reduce RCD to $\Psi$-PC. The implementation is such that it will still return the descendants of F-node but that that can be modified.

However, I do not see the point of doing this. If the goal is to learn the complete graph, why not use $\Psi$-PC directly?
