### ISSUE TITLE
The results are different everytime I run the same code, why is that? 

### ISSUE THREAD

**Issue by phamquiluan** [azamikram/rcd#6]
![image](https://github.com/azamikram/rcd/assets/24642166/99906628-887a-4a21-8a4a-96af7cd49390)

**Comment by yuuki** [comment]
It is because of this line on building skelton.
https://github.com/azamikram/rcd/blob/02a11f7399390a29c144efd4e086ffad428371d3/causallearn/utils/PCUtils/SkeletonDiscovery.py#L163
